Repository Yidu-xSkript/volunteer_connect, pull requests merged in 2023-03, with the labels that each got.

#1 Frontend's Folder structure + files created - awaiting merge
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/assets/index.css
  frontend/src/assets/logo.svg
  frontend/src/components/cards/applied.js
  frontend/src/components/cards/mission_detail_tiny.js
  frontend/src/components/cards/mission_org.js
  frontend/src/components/cards/mission_vol.js
  frontend/src/components/container.js
  frontend/src/components/filter.js
  frontend/src/components/form/button.js
  frontend/src/components/form/checkbox.js
  frontend/src/components/form/dropdown.js
  frontend/src/components/form/input.js
  frontend/src/components/form/textarea.js
  frontend/src/components/layout/footer.js
  frontend/src/components/layout/header.js
  frontend/src/components/modal/index.js
  frontend/src/components/specific/side_info_card.js
  frontend/src/data/category.json
  frontend/src/data/location.json
  frontend/src/index.js
  frontend/src/lib/axios.js
  frontend/src/pages/login/index.js
  frontend/src/pages/on_boarding/index.js
  frontend/src/pages/signup/index.js
  frontend/src/utils/utils.txt
Labels: enhancement

#2 Signup UI (Auth Layout | Form Components)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Layout/Auth/index.js
  frontend/src/assets/afr-vc.svg
  frontend/src/assets/auth-circle-white.svg
  frontend/src/assets/index.css
  frontend/src/assets/vc-auth-circle-1.svg
  frontend/src/components/form/button.js
  frontend/src/components/form/dropdown.js
  frontend/src/components/form/input.js
  frontend/src/error-page.js
  frontend/src/hooks/useToken.js
  frontend/src/index.js
  frontend/src/pages/login/index.js
  frontend/src/pages/on_boarding/index.js
  frontend/src/pages/signup/index.js
  frontend/src/utils/utils.txt
  frontend/tailwind.config.js
Labels: enhancement

#4 Login UI Complete | Renamed AuthLayout to GuestLayout
  frontend/src/Layout/Guest/index.js
  frontend/src/pages/login/index.js
  frontend/src/pages/signup/index.js
Labels: enhancement

#7 404 page created
  frontend/src/assets/404.svg
  frontend/src/index.js
  frontend/src/pages/404/index.js
Labels: enhancement

#8 Home Page Design
  frontend/src/Layout/Auth/index.js
  frontend/src/Layout/Guest/index.js
  frontend/src/components/cards/mission_home.js
  frontend/src/components/cards/mission_vol.js
  frontend/src/components/form/checkbox.js
  frontend/src/components/form/dropdown.js
  frontend/src/components/form/filter.js
  frontend/src/components/form/input.js
  frontend/src/components/form/search.js
  frontend/src/components/layout/footer.js
  frontend/src/components/layout/header.js
  frontend/src/index.js
  frontend/src/pages/homepage/index.js
  frontend/src/pages/login/index.js
  frontend/src/pages/signup/index.js
Labels: enhancement

#9 Home => added the Mission Sidebar (Details + Apply) component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/index.css
  frontend/src/components/cards/mission_detail_tiny.js
  frontend/src/components/cards/mission_home.js
  frontend/src/components/mission_sidebar.js
  frontend/src/pages/homepage/index.js
Labels: enhancement

#11 Missions (Organization Role Only)
  frontend/src/components/cards/mission_org.js
  frontend/src/index.js
  frontend/src/pages/missions/index.js
Labels: enhancement

#13 Applications Page (Please Review after #12 is resolved [merged])
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/empty.svg
  frontend/src/assets/index.css
  frontend/src/components/cards/application.js
  frontend/src/components/cards/applied.js
  frontend/src/components/cards/mission_org.js
  frontend/src/components/container.js
  frontend/src/components/filter.js
  frontend/src/components/form/button.js
  frontend/src/components/layout/footer.js
  frontend/src/components/layout/header.js
  frontend/src/components/modal/deleteMission.js
  frontend/src/components/modal/index.js
  frontend/src/components/modal/manageMission.js
  frontend/src/components/specific/side_info_card.js
  frontend/src/index.js
  frontend/src/pages/applications/index.js
  frontend/src/pages/missions/index.js
Labels: enhancement

#15 Home (Apply Modal)
  .gitignore
  frontend/src/components/form/checkbox.js
  frontend/src/components/form/filter.js
  frontend/src/components/mission_sidebar.js
  frontend/src/components/modal/Apply.js
  frontend/src/components/modal/index.js
Labels: enhancement

#18 API: adding API CRUD for Applications class model objects
  backend/volcon/applications/__init__.py
  backend/volcon/applications/app_cruds.py
Labels: enhancement

#19 Responsive Design Complete (Laptop > 1566 & > 1024, Tablet, Mobile)
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/volunteer_connect.iml
  frontend/src/Layout/Guest/index.js
  frontend/src/components/cards/application.js
  frontend/src/components/cards/mission_detail_tiny.js
  frontend/src/components/cards/mission_home.js
  frontend/src/components/cards/mission_org.js
  frontend/src/components/form/button.js
  frontend/src/components/form/checkbox.js
  frontend/src/components/form/dropdown.js
  frontend/src/components/form/filter.js
  frontend/src/components/form/search.js
  frontend/src/components/layout/footer.js
  frontend/src/components/layout/header.js
  frontend/src/components/mission_sidebar.js
  frontend/src/components/modal/index.js
  frontend/src/hooks/dimension.js
  frontend/src/pages/applicants/index.js
  frontend/src/pages/homepage/index.js
  frontend/src/pages/login/index.js
  frontend/src/pages/missions/index.js
  frontend/src/pages/on_boarding/index.js
  frontend/src/pages/profile/index.js
Labels: enhancement

#22 API: Removing Strict Slashes and Adding some Mission backend routes
  backend/volcon/auth/auth_bp.py
  backend/volcon/missions/mission_model.py
  backend/volcon/missions/mission_routes.py
Labels: enhancement

#24 Onboarding User Update API route test
  backend/models/volcon_db.py
  backend/volcon/auth/AuthController.py
  backend/volcon/org/org_cruds.py
  backend/volcon/volunteer/vol_cruds.py
Labels: enhancement

#26 API: Creation of a Blueprint of Organization backend routes.
  backend/volcon/org/org_model.py
  backend/volcon/org/org_routes.py
Labels: enhancement

#27 Auth Integration
  backend/base.py
  backend/volcon/org/org_cruds.py
  backend/volcon/volunteer/vol_cruds.py
  frontend/.env
  frontend/src/Layout/Auth/index.js
  frontend/src/Layout/Guest/index.js
  frontend/src/components/form/button.js
  frontend/src/components/form/textarea.js
  frontend/src/components/layout/header.js
  frontend/src/hooks/useUser.js
  frontend/src/lib/axios.js
  frontend/src/pages/login/index.js
  frontend/src/pages/on_boarding/index.js
  frontend/src/pages/profile/index.js
  frontend/src/pages/signup/index.js
  frontend/src/services/axios.services.js
  frontend/src/utils/API.js
  frontend/src/utils/AuthMiddleware.js
Labels: API Integration

#28 Additional Backend Code | Serializer + Relationships + New Table
  .gitignore
  backend/base.py
  backend/models/serializer/__init__.py
  backend/models/serializer/lib/__init__.py
  backend/models/serializer/lib/__pycache__/__init__.cpython-39.pyc
  backend/models/serializer/lib/__pycache__/timezones.cpython-39.pyc
  backend/models/serializer/lib/__pycache__/utils.cpython-39.pyc
  backend/models/serializer/lib/schema.py
  backend/models/serializer/lib/timezones.py
  backend/models/serializer/lib/utils.py
  backend/models/serializer/serializer.py
  backend/models/volcon_db.py
  backend/volcon/auth/AuthController.py
  backend/volcon/missions/Controller.py
  backend/volcon/missions/Model.py
  backend/volcon/missions/mission_routes.py
  backend/volcon/org/org_cruds.py
  backend/volcon/requirement/Model.py
  backend/volcon/requirement/__init__.py
  backend/volcon/volunteer/vol_cruds.py
  frontend/src/pages/on_boarding/index.js
Labels: invalid, modifications

#30 Backend Update | Search & Filter + Few API tests & changes
  .gitignore
  backend/base.py
  backend/mixin/__init__.py
  backend/mixin/authorization.py
  backend/mixin/serializer/__init__.py
  backend/mixin/serializer/lib/__init__.py
  backend/mixin/serializer/lib/__pycache__/__init__.cpython-39.pyc
  backend/mixin/serializer/lib/__pycache__/timezones.cpython-39.pyc
  backend/mixin/serializer/lib/__pycache__/utils.cpython-39.pyc
  backend/mixin/serializer/lib/schema.py
  backend/mixin/serializer/lib/timezones.py
  backend/mixin/serializer/lib/utils.py
  backend/mixin/serializer/serializer.py
  backend/models/volcon_db.py
  backend/volcon/applications/Controller.py
  backend/volcon/applications/Model.py
  backend/volcon/applications/app_cruds.py
  backend/volcon/auth/Controller.py
  backend/volcon/missions/Controller.py
  backend/volcon/missions/Model.py
  backend/volcon/requirement/Model.py
Labels: enhancement, modifications

#29 API: New Application entries + Displaying mission's status
  backend/volcon/missions/Controller.py
Labels: enhancement

#32 Integration Complete
  .gitignore
  backend/base.py
  backend/models/serializer/__init__.py
  backend/models/serializer/lib/__init__.py
  backend/models/serializer/lib/__pycache__/__init__.cpython-39.pyc
  backend/models/serializer/lib/__pycache__/timezones.cpython-39.pyc
  backend/models/serializer/lib/__pycache__/utils.cpython-39.pyc
  backend/models/serializer/lib/schema.py
  backend/models/serializer/lib/timezones.py
  backend/models/serializer/lib/utils.py
  backend/models/serializer/serializer.py
  backend/models/volcon_db.py
  backend/volcon/applications/Controller.py
  backend/volcon/applications/Model.py
  backend/volcon/auth/AuthController.py
  backend/volcon/auth/Controller.py
  backend/volcon/auth/authorization.py
  backend/volcon/missions/Controller.py
  backend/volcon/missions/Model.py
  backend/volcon/org/org_routes.py
  frontend/package-lock.json
  frontend/package.json
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/site.webmanifest
  frontend/src/Layout/Guest/index.js
  frontend/src/assets/logo.svg
  frontend/src/components/cards/application.js
  frontend/src/components/cards/mission_home.js
  frontend/src/components/cards/mission_org.js
  frontend/src/components/form/button.js
  frontend/src/components/form/filter.js
  frontend/src/components/form/input.js
  frontend/src/components/form/search.js
  frontend/src/components/layout/footer.js
  frontend/src/components/layout/header.js
  frontend/src/components/location.js
  frontend/src/components/mission_sidebar.js
  frontend/src/components/modal/Apply.js
  frontend/src/components/modal/deleteMission.js
  frontend/src/components/modal/index.js
  frontend/src/components/modal/manageMission.js
  frontend/src/data/category.json
  frontend/src/data/location.json
  frontend/src/hooks/useMission.js
  frontend/src/hooks/useSearch.js
  frontend/src/index.js
  frontend/src/pages/applicants/index.js
  frontend/src/pages/applications/index.js
  frontend/src/pages/homepage/index.js
  frontend/src/pages/missions/index.js
  frontend/src/pages/profile/index.js
  frontend/src/services/axios.services.js
Labels: bug, enhancement, modifications, API Integration
